package com.example.demo.springsecurity;

import org.springframework.context.annotation.Configuration;
import org.springframework.http.HttpMethod;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.annotation.web.configurers.ExpressionUrlAuthorizationConfigurer;

@Configuration
@EnableWebSecurity//(debug = true)
public class WebSecurityConfig {


    private void addAuthorisation(ExpressionUrlAuthorizationConfigurer<HttpSecurity>.ExpressionInterceptUrlRegistry config) {
        config
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')").antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')").antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')")
                .antMatchers(HttpMethod.GET, "/api/test/{justID}")
                .access("hasAuthority('DEMO_READ')");
    }
}
